
package q2java;

/**
 * This interface was generated by a SmartGuide.
 * 
 */
public interface NativePlayer {

/**
 * This method was created by a SmartGuide.
 * @param loadgame boolean
 */
public abstract void begin(boolean loadgame);
/**
 * This method was created by a SmartGuide.
 */
public abstract void command();
/**
 * This method was created by a SmartGuide.
 */
public abstract void disconnect();
/**
 * This method was created by a SmartGuide.
 * @param cmd q2java.UserCmd
 */
public abstract void think();
/**
 * This method was created by a SmartGuide.
 * @param userinfo java.lang.String
 */
public abstract void userinfoChanged(String userinfo);
}