
package q2java;

/**
 * This interface was generated by a SmartGuide.
 * 
 */
public interface NativePlayer {

/**
 * This method was created by a SmartGuide.
 * @param loadgame boolean
 */
public abstract void playerBegin(boolean loadgame);
/**
 * This method was created by a SmartGuide.
 */
public abstract void playerCommand();
/**
 * This method was created by a SmartGuide.
 */
public abstract void playerDisconnect();
/**
 * This method was created by a SmartGuide.
 * @param userinfo java.lang.String
 */
public abstract void playerInfoChanged(String userinfo);
/**
 * This method was created by a SmartGuide.
 * @param cmd q2java.UserCmd
 */
public abstract void playerThink(UserCmd cmd);
}