
package q2java;

/**
 * This class was generated by a SmartGuide.
 * 
 */
public class PMoveResults 
	{
	public NativeEntity[]	fTouched;
	public float			fViewHeight;
	public NativeEntity	fGroundEntity;
	public int			fWaterType;
	public int 			fWaterLevel;
	
/**
 * This method was created by a SmartGuide.
 */
private PMoveResults(NativeEntity[] touched, float viewHeight,
	NativeEntity groundEntity, int waterType, int waterLevel) 
	{
	fTouched = touched;
	fViewHeight = viewHeight;
	fGroundEntity = groundEntity;
	fWaterType = waterType;
	fWaterLevel = waterLevel;	
	}
/**
 * This method was created by a SmartGuide.
 * @return java.lang.String
 */
public String toString() 
	{
	StringBuffer sb = new StringBuffer();
	if (fTouched == null)		
		sb.append("fTouched: (null)\n");
	else
		{
		sb.append("fTouched:\n");
		for (int i = 0; i < fTouched.length; i++)
			sb.append("    " + fTouched[i] + "\n");
		}		
	sb.append("fViewHeight: " + fViewHeight + "\n");
	sb.append("fGroundEntity: " + fGroundEntity + "\n");
	sb.append("fWaterType: " + fWaterType + " fWaterLevel: " + fWaterLevel + "\n");
	return sb.toString();
	}
}