
/**
 * This class was generated by a SmartGuide.
 * 
 */
 
import java.io.*;  
 
class Q2JavaSecurityManager extends SecurityManager 
	{
	String fSandboxPrefix;
	
/**
 * Q2JavaSecurityManager constructor comment.
 */ 
protected Q2JavaSecurityManager(String gamePath) 
	{
	super();
	File gameDir = new File(gamePath);
	File sandboxDir = new File(gameDir, "sandbox");
	fSandboxPrefix = sandboxDir.getPath() + File.separator;
	}
/**
 * This method was created by a SmartGuide.
 * @param file java.lang.String
 */
public void checkDelete(String filename) 
	{
	Engine.dprint("checkDelete(\"" + filename + "\")\n");
	checkSandbox(filename);
	}
/**
 * This method was created by a SmartGuide.
 * @param clazz java.lang.Class
 * @param which int
 */
public void checkMemberAccess(Class clazz, int which) 
	{
	Engine.dprint("checkMemberAccess(" + clazz + ", " + which + ")\n");
	}
/**
 * This method was created by a SmartGuide.
 */
public void checkPropertyAccess(String key) 
	{
	Engine.dprint("checkPropertyAccess(\"" + key + "\")\n");
	}
/**
 * This method was created by a SmartGuide.
 * @param filename java.lang.String
 */
public void checkRead(String filename) 
	{
	Engine.dprint("checkRead(\"" + filename + "\")\n");
	checkSandbox(filename);
	}
/**
 * This method was created by a SmartGuide.
 * @return boolean
 * @param filename java.lang.String
 */
private void checkSandbox(String filename) 
	{
	File f = new File(filename);
	try
		{
		filename = f.getCanonicalPath();
		}
	catch (IOException e)
		{
		throw new SecurityException(e.getMessage());
		}
				
	if (!filename.startsWith(fSandboxPrefix))
		throw new SecurityException(filename + " is not in the protected sandbox: " + fSandboxPrefix);
	}
/**
 * This method was created by a SmartGuide.
 * @param filename java.lang.String
 */
public void checkWrite(String filename) 
	{
	Engine.dprint("checkWrite(\"" + filename + "\")\n");
	checkSandbox(filename);
	}
}