
package q2jgame;

/**
 * This class was generated by a SmartGuide.
 * 
 */
class LoadedModule
	{
	String fPackageName;
	String fAlias;
	GameModule fModule;
	
/**
 * Compare this LoadedPackage with another one, or a String..looking
 * for matching aliases.
 * @return boolean
 * @param obj java.lang.Object
 */
public boolean equals(Object obj) 
	{
	if (obj instanceof String)
		return ((String) obj).equalsIgnoreCase(fAlias);
	if (obj instanceof LoadedModule)
		return ((LoadedModule) obj).fAlias.equalsIgnoreCase(fAlias);
		
	return false;
	}
/**
 * This method was created by a SmartGuide.
 * @return java.lang.String
 */
public String toString() 
	{
	return "Loaded Package: " + fAlias + "(" + fPackageName + ")";
	}
}