
package q2jgame;

/**
 * This class was generated by a SmartGuide.
 * 
 */
public class AmmoPack 
	{
	int fAmount;
	int fMaxAmount;
	int fIcon;
	
/**
 * This method was created by a SmartGuide.
 * @param count int
 * @param icon int
 */
public AmmoPack (int maxCount, int icon) 
	{
	fMaxAmount = maxCount;
	fIcon = icon;
	}
}