
package q2jgame;

/**
 * This interface was generated by a SmartGuide.
 * 
 */
 
import q2jgame.*;
 
public interface AreaTriggerUser 
	{
	
/**
 * This method was created by a SmartGuide.
 */
public void areaTrigger(Player touchedBy);
}