
package q2jgame;

/**
 * This class was generated by a SmartGuide.
 * 
 */
 
import q2java.*;
 
public class BlasterBolt extends GameEntity 
	{
	
/**
 * BlasterBolt constructor comment.
 * @exception q2java.GameException The exception description.
 */
public BlasterBolt(GameEntity owner, Vec3 start, Vec3 dir, int damage, int speed, int effect) throws q2java.GameException 
	{
	super();
	setOrigin(start);
	setAngles(dir.toAngles());
	dir.normalize().scale(speed);
	setVelocity(dir);
	setClipmask(MASK_SHOT);
	setSolid(SOLID_BBOX);
	setEffects(effect);
	setModelIndex(Engine.modelIndex("models/objects/laser/tris.md2"));
	setSound(Engine.soundIndex("misc/lasfly.wav"));
	setOwner(owner);
	fThinkTime = (float)Game.fGameTime + 2;
//	bolt->think = G_FreeEdict;
//	bolt->dmg = damage;
	linkEntity();
/*
	if (self->client)
		check_dodge (self, bolt->s.origin, dir, speed);

	tr = gi.trace (self->s.origin, NULL, NULL, bolt->s.origin, bolt, MASK_SHOT);
	if (tr.fraction < 1.0)
		{
		VectorMA (bolt->s.origin, -10, dir, bolt->s.origin);
		bolt->touch (bolt, tr.ent, NULL, NULL);
		}		
*/
	}
/**
 * Go away the first chance we get to think
 */
public void runFrame() 
	{
	if (Game.fGameTime >= fThinkTime)
		{
		freeEntity();
		return;
		}
		
	setOrigin(getOrigin().add(getVelocity().scale(Engine.SECONDS_PER_FRAME)));		
	}
}	