
package q2jgame;

/**
 * This interface was generated by a SmartGuide.
 * 
 */
public interface PrintListener 
	{
	
/**
 * Print a broadcast message.
 * @param flags int
 * @param msg java.lang.String
 */
public void bprint(int flags, String msg);
/**
 * Print a debugging message.
 * @param msg java.lang.String
 */
public void dprint(String msg);
}