/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class q2java_NativeEntity */

#ifndef _Included_q2java_NativeEntity
#define _Included_q2java_NativeEntity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     q2java_NativeEntity
 * Method:    getPotentialPushed0
 * Signature: (IFFFFFFI)[Lq2java/NativeEntity;
 */
static jobjectArray JNICALL Java_q2java_NativeEntity_getPotentialPushed0
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     q2java_NativeEntity
 * Method:    pMove0
 * Signature: (IBBSSSSSSBBI)Lq2java/PMoveResults;
 */
static jobject JNICALL Java_q2java_NativeEntity_pMove0
  (JNIEnv *, jclass, jint, jbyte, jbyte, jshort, jshort, jshort, jshort, jshort, jshort, jbyte, jbyte, jint);

/*
 * Class:     q2java_NativeEntity
 * Method:    getRadiusEntities0
 * Signature: (IFZZ)[Lq2java/NativeEntity;
 */
static jobjectArray JNICALL Java_q2java_NativeEntity_getRadiusEntities0
  (JNIEnv *, jclass, jint, jfloat, jboolean, jboolean);

/*
 * Class:     q2java_NativeEntity
 * Method:    getPlayerInfo0
 * Signature: (I)Ljava/lang/String;
 */
static jstring JNICALL Java_q2java_NativeEntity_getPlayerInfo0
  (JNIEnv *, jclass, jint);

/*
 * Class:     q2java_NativeEntity
 * Method:    setFloat0
 * Signature: (IIFFFF)V
 */
static void JNICALL Java_q2java_NativeEntity_setFloat0
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     q2java_NativeEntity
 * Method:    setEntity
 * Signature: (III)V
 */
static void JNICALL Java_q2java_NativeEntity_setEntity
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     q2java_NativeEntity
 * Method:    getVec3
 * Signature: (III)Ljavax/vecmath/Tuple3f;
 */
static jobject JNICALL Java_q2java_NativeEntity_getVec3
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     q2java_NativeEntity
 * Method:    getPlayerListener0
 * Signature: (I)Lq2java/PlayerListener;
 */
static jobject JNICALL Java_q2java_NativeEntity_getPlayerListener0
  (JNIEnv *, jclass, jint);

/*
 * Class:     q2java_NativeEntity
 * Method:    getShort
 * Signature: (II)S
 */
static jshort JNICALL Java_q2java_NativeEntity_getShort
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     q2java_NativeEntity
 * Method:    traceMove0
 * Signature: (IIF)Lq2java/TraceResults;
 */
static jobject JNICALL Java_q2java_NativeEntity_traceMove0
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     q2java_NativeEntity
 * Method:    cprint0
 * Signature: (IILjava/lang/String;)V
 */
static void JNICALL Java_q2java_NativeEntity_cprint0
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     q2java_NativeEntity
 * Method:    unlinkEntity0
 * Signature: (I)V
 */
static void JNICALL Java_q2java_NativeEntity_unlinkEntity0
  (JNIEnv *, jclass, jint);

/*
 * Class:     q2java_NativeEntity
 * Method:    setInt
 * Signature: (III)V
 */
static void JNICALL Java_q2java_NativeEntity_setInt
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     q2java_NativeEntity
 * Method:    setStat0
 * Signature: (IIS)V
 */
static void JNICALL Java_q2java_NativeEntity_setStat0
  (JNIEnv *, jclass, jint, jint, jshort);

/*
 * Class:     q2java_NativeEntity
 * Method:    freeEntity0
 * Signature: (I)V
 */
static void JNICALL Java_q2java_NativeEntity_freeEntity0
  (JNIEnv *, jclass, jint);

/*
 * Class:     q2java_NativeEntity
 * Method:    centerprint0
 * Signature: (ILjava/lang/String;)V
 */
static void JNICALL Java_q2java_NativeEntity_centerprint0
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     q2java_NativeEntity
 * Method:    setVec3
 * Signature: (IIFFF)V
 */
static void JNICALL Java_q2java_NativeEntity_setVec3
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     q2java_NativeEntity
 * Method:    allocateEntity
 * Signature: (I)I
 */
static jint JNICALL Java_q2java_NativeEntity_allocateEntity
  (JNIEnv *, jclass, jint);

/*
 * Class:     q2java_NativeEntity
 * Method:    getInt
 * Signature: (II)I
 */
static jint JNICALL Java_q2java_NativeEntity_getInt
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     q2java_NativeEntity
 * Method:    getFloat
 * Signature: (II)F
 */
static jfloat JNICALL Java_q2java_NativeEntity_getFloat
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     q2java_NativeEntity
 * Method:    setShort
 * Signature: (IIS)V
 */
static void JNICALL Java_q2java_NativeEntity_setShort
  (JNIEnv *, jclass, jint, jint, jshort);

/*
 * Class:     q2java_NativeEntity
 * Method:    linkEntity0
 * Signature: (I)V
 */
static void JNICALL Java_q2java_NativeEntity_linkEntity0
  (JNIEnv *, jclass, jint);

/*
 * Class:     q2java_NativeEntity
 * Method:    getByte
 * Signature: (II)B
 */
static jbyte JNICALL Java_q2java_NativeEntity_getByte
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     q2java_NativeEntity
 * Method:    getEntity
 * Signature: (II)Lq2java/NativeEntity;
 */
static jobject JNICALL Java_q2java_NativeEntity_getEntity
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     q2java_NativeEntity
 * Method:    sound0
 * Signature: (FFFIIIFFFI)V
 */
static void JNICALL Java_q2java_NativeEntity_sound0
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jint, jint, jint, jfloat, jfloat, jfloat, jint);

/*
 * Class:     q2java_NativeEntity
 * Method:    getBoxEntities0
 * Signature: (II)[Lq2java/NativeEntity;
 */
static jobjectArray JNICALL Java_q2java_NativeEntity_getBoxEntities0
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     q2java_NativeEntity
 * Method:    copySettings0
 * Signature: (II)V
 */
static void JNICALL Java_q2java_NativeEntity_copySettings0
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     q2java_NativeEntity
 * Method:    setByte
 * Signature: (IIB)V
 */
static void JNICALL Java_q2java_NativeEntity_setByte
  (JNIEnv *, jclass, jint, jint, jbyte);

/*
 * Class:     q2java_NativeEntity
 * Method:    setModel0
 * Signature: (ILjava/lang/String;)V
 */
static void JNICALL Java_q2java_NativeEntity_setModel0
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     q2java_NativeEntity
 * Method:    setPlayerListener0
 * Signature: (ILq2java/PlayerListener;)V
 */
static void JNICALL Java_q2java_NativeEntity_setPlayerListener0
  (JNIEnv *, jclass, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
