/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class q2java_ConsoleOutputStream */

#ifndef _Included_q2java_ConsoleOutputStream
#define _Included_q2java_ConsoleOutputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     q2java_ConsoleOutputStream
 * Method:    write
 * Signature: (I)V
 */
void JNICALL Java_q2java_ConsoleOutputStream_write__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     q2java_ConsoleOutputStream
 * Method:    write
 * Signature: ([BII)V
 */
void JNICALL Java_q2java_ConsoleOutputStream_write___3BII
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
