/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Engine */

#ifndef _Included_Engine
#define _Included_Engine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Engine
 * Method:    args
 * Signature: ()Ljava/lang/String;
 */
jstring JNICALL Java_Engine_args
  (JNIEnv *, jclass);

/*
 * Class:     Engine
 * Method:    bprint
 * Signature: (ILjava/lang/String;)V
 */
void JNICALL Java_Engine_bprint
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     Engine
 * Method:    write0
 * Signature: (Ljava/lang/Object;FFFII)V
 */
void JNICALL Java_Engine_write0
  (JNIEnv *, jclass, jobject, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     Engine
 * Method:    getGamePath
 * Signature: ()Ljava/lang/String;
 */
jstring JNICALL Java_Engine_getGamePath
  (JNIEnv *, jclass);

/*
 * Class:     Engine
 * Method:    addCommandString
 * Signature: (Ljava/lang/String;)V
 */
void JNICALL Java_Engine_addCommandString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Engine
 * Method:    pointContents0
 * Signature: (FFF)I
 */
jint JNICALL Java_Engine_pointContents0
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     Engine
 * Method:    areasConnected
 * Signature: (II)Z
 */
jboolean JNICALL Java_Engine_areasConnected
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     Engine
 * Method:    error
 * Signature: (Ljava/lang/String;)V
 */
void JNICALL Java_Engine_error
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Engine
 * Method:    debugGraph
 * Signature: (FI)V
 */
void JNICALL Java_Engine_debugGraph
  (JNIEnv *, jclass, jfloat, jint);

/*
 * Class:     Engine
 * Method:    boxEntities0
 * Signature: (FFFFFFII)[LNativeEntity;
 */
jobjectArray JNICALL Java_Engine_boxEntities0
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     Engine
 * Method:    soundIndex
 * Signature: (Ljava/lang/String;)I
 */
jint JNICALL Java_Engine_soundIndex
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Engine
 * Method:    argc
 * Signature: ()I
 */
jint JNICALL Java_Engine_argc
  (JNIEnv *, jclass);

/*
 * Class:     Engine
 * Method:    modelIndex
 * Signature: (Ljava/lang/String;)I
 */
jint JNICALL Java_Engine_modelIndex
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Engine
 * Method:    argv
 * Signature: (I)Ljava/lang/String;
 */
jstring JNICALL Java_Engine_argv
  (JNIEnv *, jclass, jint);

/*
 * Class:     Engine
 * Method:    configString
 * Signature: (ILjava/lang/String;)V
 */
void JNICALL Java_Engine_configString
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     Engine
 * Method:    imageIndex
 * Signature: (Ljava/lang/String;)I
 */
jint JNICALL Java_Engine_imageIndex
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Engine
 * Method:    trace0
 * Signature: (FFFFFFFFFFFFLNativeEntity;I)LTraceResults;
 */
jobject JNICALL Java_Engine_trace0
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jobject, jint);

/*
 * Class:     Engine
 * Method:    setAreaPortalState
 * Signature: (IZ)V
 */
void JNICALL Java_Engine_setAreaPortalState
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     Engine
 * Method:    dprint
 * Signature: (Ljava/lang/String;)V
 */
void JNICALL Java_Engine_dprint
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Engine
 * Method:    inP0
 * Signature: (FFFFFFI)Z
 */
jboolean JNICALL Java_Engine_inP0
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

#ifdef __cplusplus
}
#endif
#endif
