/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativePlayer */

#ifndef _Included_NativePlayer
#define _Included_NativePlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativePlayer
 * Method:    cprint0
 * Signature: (IILjava/lang/String;)V
 */
void JNICALL Java_NativePlayer_cprint0
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     NativePlayer
 * Method:    pMove0
 * Signature: (I)LPMoveResults;
 */
jobject JNICALL Java_NativePlayer_pMove0
  (JNIEnv *, jclass, jint);

/*
 * Class:     NativePlayer
 * Method:    setStat0
 * Signature: (IIS)V
 */
void JNICALL Java_NativePlayer_setStat0
  (JNIEnv *, jclass, jint, jint, jshort);

/*
 * Class:     NativePlayer
 * Method:    setFloat0
 * Signature: (IIFFFF)V
 */
void JNICALL Java_NativePlayer_setFloat0
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     NativePlayer
 * Method:    centerprint0
 * Signature: (ILjava/lang/String;)V
 */
void JNICALL Java_NativePlayer_centerprint0
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
