/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class q2java_CVar */

#ifndef _Included_q2java_CVar
#define _Included_q2java_CVar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     q2java_CVar
 * Method:    getFloat0
 * Signature: (I)F
 */
jfloat JNICALL Java_q2java_CVar_getFloat0
  (JNIEnv *, jclass, jint);

/*
 * Class:     q2java_CVar
 * Method:    getString0
 * Signature: (I)Ljava/lang/String;
 */
jstring JNICALL Java_q2java_CVar_getString0
  (JNIEnv *, jclass, jint);

/*
 * Class:     q2java_CVar
 * Method:    cvar0
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
jint JNICALL Java_q2java_CVar_cvar0
  (JNIEnv *, jclass, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
