/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class q2java_Engine */

#ifndef _Included_q2java_Engine
#define _Included_q2java_Engine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     q2java_Engine
 * Method:    args
 * Signature: ()Ljava/lang/String;
 */
jstring JNICALL Java_q2java_Engine_args
  (JNIEnv *, jclass);

/*
 * Class:     q2java_Engine
 * Method:    bprint
 * Signature: (ILjava/lang/String;)V
 */
void JNICALL Java_q2java_Engine_bprint
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     q2java_Engine
 * Method:    write0
 * Signature: (Ljava/lang/Object;FFFII)V
 */
void JNICALL Java_q2java_Engine_write0
  (JNIEnv *, jclass, jobject, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     q2java_Engine
 * Method:    getGamePath
 * Signature: ()Ljava/lang/String;
 */
jstring JNICALL Java_q2java_Engine_getGamePath
  (JNIEnv *, jclass);

/*
 * Class:     q2java_Engine
 * Method:    debugLog
 * Signature: (Ljava/lang/String;)V
 */
void JNICALL Java_q2java_Engine_debugLog
  (JNIEnv *, jclass, jstring);

/*
 * Class:     q2java_Engine
 * Method:    addCommandString
 * Signature: (Ljava/lang/String;)V
 */
void JNICALL Java_q2java_Engine_addCommandString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     q2java_Engine
 * Method:    pointContents0
 * Signature: (FFF)I
 */
jint JNICALL Java_q2java_Engine_pointContents0
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     q2java_Engine
 * Method:    boxEntities0
 * Signature: (FFFFFFI)[Lq2java/NativeEntity;
 */
jobjectArray JNICALL Java_q2java_Engine_boxEntities0
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     q2java_Engine
 * Method:    areasConnected
 * Signature: (II)Z
 */
jboolean JNICALL Java_q2java_Engine_areasConnected
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     q2java_Engine
 * Method:    error
 * Signature: (Ljava/lang/String;)V
 */
void JNICALL Java_q2java_Engine_error
  (JNIEnv *, jclass, jstring);

/*
 * Class:     q2java_Engine
 * Method:    debugGraph
 * Signature: (FI)V
 */
void JNICALL Java_q2java_Engine_debugGraph
  (JNIEnv *, jclass, jfloat, jint);

/*
 * Class:     q2java_Engine
 * Method:    soundIndex
 * Signature: (Ljava/lang/String;)I
 */
jint JNICALL Java_q2java_Engine_soundIndex
  (JNIEnv *, jclass, jstring);

/*
 * Class:     q2java_Engine
 * Method:    argc
 * Signature: ()I
 */
jint JNICALL Java_q2java_Engine_argc
  (JNIEnv *, jclass);

/*
 * Class:     q2java_Engine
 * Method:    modelIndex
 * Signature: (Ljava/lang/String;)I
 */
jint JNICALL Java_q2java_Engine_modelIndex
  (JNIEnv *, jclass, jstring);

/*
 * Class:     q2java_Engine
 * Method:    argv
 * Signature: (I)Ljava/lang/String;
 */
jstring JNICALL Java_q2java_Engine_argv
  (JNIEnv *, jclass, jint);

/*
 * Class:     q2java_Engine
 * Method:    configString
 * Signature: (ILjava/lang/String;)V
 */
void JNICALL Java_q2java_Engine_configString
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     q2java_Engine
 * Method:    imageIndex
 * Signature: (Ljava/lang/String;)I
 */
jint JNICALL Java_q2java_Engine_imageIndex
  (JNIEnv *, jclass, jstring);

/*
 * Class:     q2java_Engine
 * Method:    setAreaPortalState
 * Signature: (IZ)V
 */
void JNICALL Java_q2java_Engine_setAreaPortalState
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     q2java_Engine
 * Method:    dprint
 * Signature: (Ljava/lang/String;)V
 */
void JNICALL Java_q2java_Engine_dprint
  (JNIEnv *, jclass, jstring);

/*
 * Class:     q2java_Engine
 * Method:    inP0
 * Signature: (FFFFFFI)Z
 */
jboolean JNICALL Java_q2java_Engine_inP0
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     q2java_Engine
 * Method:    trace0
 * Signature: (FFFFFFFFFFFFLq2java/NativeEntity;II)Lq2java/TraceResults;
 */
jobject JNICALL Java_q2java_Engine_trace0
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
